Repository KinsonDigital/.github, pull requests merged in 2022-10, with the labels that each got.

#5 Add qa testing issue template
  .github/ISSUE_TEMPLATE/qa-testing-template.yml
Labels: documentation, high priority

#16 🚧Update QA testing template
  .github/ISSUE_TEMPLATE/qa-testing-template.yml
Labels: documentation, low priority

#17 🚧Change release todo issue templates
  .github/ISSUE_TEMPLATE/preview-release-todo-issue-template.yml
  .github/ISSUE_TEMPLATE/production-release-todo-issue-template.yml
Labels: high priority

#23 🚧Add security policy file for organization
  .github/SECURITY.md
Labels: documentation, high priority
